name: Build OpenWrt CUPS + AirPrint IPKs

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout this repo
      uses: actions/checkout@v4

    - name: Install build dependencies
      run: |
        sudo apt update
        sudo apt install -y build-essential clang flex bison g++ gawk gcc-multilib g++-multilib \
          gettext git libncurses-dev libssl-dev rsync unzip zlib1g-dev file wget python3 python3-pip python3-setuptools

    - name: Clone OpenWrt source
      run: |
        git clone --depth=1 https://git.openwrt.org/openwrt/openwrt.git
        cd openwrt
        ./scripts/feeds update -a
        ./scripts/feeds install -a

    - name: Clone OpenWrt packages.git for cups & avahi
      run: |
        cd openwrt/package
        git clone --depth=1 https://github.com/openwrt/packages.git temp-packages
        cp -r temp-packages/print/cups .
        cp -r temp-packages/print/cups-filters .
        cp -r temp-packages/net/avahi .
        rm -rf temp-packages

    - name: Generate .config for target + packages
      run: |
        cd openwrt
        echo "CONFIG_TARGET_ath79=y" >> .config
        echo "CONFIG_TARGET_ath79_nand=y" >> .config
        echo "CONFIG_TARGET_ath79_nand_DEVICE_wndr4300=y" >> .config
        echo "CONFIG_PACKAGE_cups=y" >> .config
        echo "CONFIG_PACKAGE_cups-filters=y" >> .config
        echo "CONFIG_PACKAGE_avahi-daemon=y" >> .config
        echo "CONFIG_PACKAGE_libgnutls=y" >> .config
        echo "CONFIG_PACKAGE_libavahi=y" >> .config
        echo "CONFIG_PACKAGE_libusb-1.0=y" >> .config
        make defconfig

    - name: Download sources
      run: |
        cd openwrt
        make download -j$(nproc) || make download -j1 V=s

    - name: Compile packages
      run: |
        cd openwrt
        make package/cups/compile -j$(nproc) V=s
        make package/cups-filters/compile -j$(nproc) V=s
        make package/avahi/compile -j$(nproc) V=s

    - name: Upload compiled .ipk
      uses: actions/upload-artifact@v4
      with:
        name: openwrt-cups-airprint-ipks
        path: openwrt/bin/packages/mips_24kc/**/*.ipk
