name: Build CUPS with AirPrint Support

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: 准备空间
      run: |
        sudo swapoff -a
        sudo fallocate -l 6G /swapfile
        sudo chmod 600 /swapfile
        sudo mkswap /swapfile
        sudo swapon /swapfile

    - name: 安装依赖
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          build-essential clang flex g++ gawk gcc-multilib g++-multilib \
          gettext git libncurses-dev libssl-dev python3 python3-pip unzip \
          zlib1g-dev file wget libelf-dev ecj java-propose-classpath \
          python3-distutils rsync subversion

    - name: 克隆 OpenWrt 源码
      run: |
        git clone https://github.com/openwrt/openwrt.git
        cd openwrt
        ./scripts/feeds update -a
        ./scripts/feeds install -a

    - name: 拉取 OpenWrt 包 feeds（包括打印服务）
      run: |
        cd openwrt
        ./scripts/feeds update packages luci
        ./scripts/feeds install cups cups-filters avahi-daemon avahi-dnsconfd

    - name: 设置编译配置
      run: |
        cd openwrt
        cat >> .config <<EOF
        CONFIG_TARGET_ath79=y
        CONFIG_TARGET_ath79_nand=y
        CONFIG_TARGET_ath79_nand_DEVICE_netgear_wndr4300=y

        CONFIG_PACKAGE_cups=y
        CONFIG_PACKAGE_cups-filters=y
        CONFIG_PACKAGE_avahi-daemon=y
        CONFIG_PACKAGE_avahi-dnsconfd=y
        CONFIG_PACKAGE_libavahi=y
        CONFIG_PACKAGE_libdaemon=y
        CONFIG_PACKAGE_libexpat=y
        CONFIG_PACKAGE_libiconv-full=y
        CONFIG_PACKAGE_libjpeg=y
        CONFIG_PACKAGE_libpng=y
        CONFIG_PACKAGE_libusb-1.0=y
        CONFIG_PACKAGE_zlib=y
        EOF

        make defconfig

    - name: 编译
      run: |
        cd openwrt
        make -j$(nproc) download
        make -j$(nproc) V=s

    - name: 上传软件包
      uses: actions/upload-artifact@v4
      with:
        name: cups-airprint-packages
        path: openwrt/bin/packages/mips_24kc/
