name: Build CUPS 2.3.6 with AirPrint for OpenWrt (ath79/nand)

on:
  workflow_dispatch:
  push:
    branches: [ main ]

env:
  OPENWRT_SDK_URL: https://downloads.openwrt.org/releases/23.05.3/targets/ath79/nand/openwrt-sdk-23.05.3-ath79-nand_gcc-12.3.0_musl.Linux-x86_64.tar.xz

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libncurses5-dev gawk git subversion \
                                  libssl-dev gettext unzip python3 python3-pip file wget

      - name: Download & unpack SDK
        run: |
          wget -q $OPENWRT_SDK_URL -O sdk.tar.xz
          tar -xf sdk.tar.xz
          mv openwrt-sdk* sdk

      - name: Copy custom cups package
        run: |
          mkdir -p sdk/package/cups
          cp .github/cups-Makefile sdk/package/cups/Makefile

      - name: Download sources & build
        run: |
          cd sdk
          ./scripts/feeds update -a
          ./scripts/feeds install -a
          make package/cups/download  V=s
          make package/cups/prepare   V=s
          make package/cups/compile   V=s -j$(nproc)

      - name: Collect artifacts
        run: |
          cd sdk
          mkdir -p ../artifacts
          find bin/packages -type f -name '*cups*.ipk' -exec cp {} ../artifacts/ \;

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: cups-2.3.6-ath79-nand-ipks
          path: artifacts/
