# .github/workflows/build-cups.yml
name: Build CUPS with AirPrint for OpenWrt (ath79/nand)

on:
  workflow_dispatch:      # 允许手动触发
  push:
    branches: [ main ]

env:
  OPENWRT_SDK_URL: https://downloads.openwrt.org/releases/23.05.3/targets/ath79/nand/openwrt-sdk-23.05.3-ath79-nand_gcc-12.3.0_musl.Linux-x86_64.tar.xz
  FEEDS_CUPS_URL: https://github.com/TheMMcOfficial/lede-cups.git
  FEEDS_CONF: feeds.conf.default

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libncurses5-dev gawk git subversion \
                                  libssl-dev gettext unzip python3 python3-pip file wget

      - name: Download & unpack SDK
        run: |
          wget -q $OPENWRT_SDK_URL -O sdk.tar.xz
          tar -xf sdk.tar.xz
          mv openwrt-sdk* sdk
          cd sdk
          echo "src-git cups $FEEDS_CUPS_URL" >> $FEEDS_CONF
          ./scripts/feeds update -a
          ./scripts/feeds install -a

      - name: Configure & build cups
        run: |
          cd sdk
          make defconfig
          echo 'CONFIG_PACKAGE_cups=y' >> .config
          echo 'CONFIG_PACKAGE_cups-browsed=y' >> .config
          echo 'CONFIG_PACKAGE_avahi-daemon=y' >> .config
          echo 'CONFIG_PACKAGE_libcups=y' >> .config
          make -j$(nproc) package/cups/compile

      - name: Collect artifacts
        run: |
          cd sdk
          mkdir -p ../artifacts
          find bin/packages -type f -name '*.ipk' -exec cp {} ../artifacts/ \;

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: cups-ath79-nand-ipks
          path: artifacts/
