name: Build OpenWrt CUPS + AirPrint for WNDR4300

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout OpenWrt
      uses: actions/checkout@v3
      with:
        repository: openwrt/openwrt
        ref: master
        path: openwrt

    - name: Install Dependencies
      run: |
        sudo apt update
        sudo apt install -y build-essential clang flex bison g++ gawk \
          gcc-multilib gettext git libncurses-dev libssl-dev python3 \
          python3-pip unzip wget zlib1g-dev file libelf-dev ecj fastjar java-propose-classpath \
          python3-setuptools python3-dev
        python3 -m pip install --upgrade pip
        python3 -m pip install setuptools

    - name: Update Feeds
      working-directory: openwrt
      run: |
        ./scripts/feeds update -a
        ./scripts/feeds install -a

    - name: Configure Target
      working-directory: openwrt
      run: |
        make defconfig
        echo "CONFIG_TARGET_ath79=y" >> .config
        echo "CONFIG_TARGET_ath79_nand=y" >> .config
        echo "CONFIG_TARGET_ath79_nand_DEVICE_netgear_wndr4300=y" >> .config
        echo "CONFIG_PACKAGE_cups=y" >> .config
        echo "CONFIG_PACKAGE_cups-filters=y" >> .config
        echo "CONFIG_PACKAGE_avahi-daemon=y" >> .config
        echo "CONFIG_PACKAGE_avahi-dnsconfd=y" >> .config
        echo "CONFIG_PACKAGE_libavahi=y" >> .config
        echo "CONFIG_PACKAGE_libdaemon=y" >> .config
        echo "CONFIG_PACKAGE_libgcrypt=y" >> .config
        echo "CONFIG_PACKAGE_libgnutls=y" >> .config
        echo "CONFIG_PACKAGE_libusb-1.0=y" >> .config
        make defconfig

    - name: Download Sources
      working-directory: openwrt
      run: make download -j8

    - name: Build CUPS + AirPrint Packages
      working-directory: openwrt
      run: make package/cups/compile package/cups-filters/compile package/avahi/compile -j$(nproc) V=s

    - name: Upload Packages as Artifact
      uses: actions/upload-artifact@v3
      with:
        name: cups-airprint-ipks
        path: |
          openwrt/bin/packages/mips_24kc/base/cups_*.ipk
          openwrt/bin/packages/mips_24kc/base/cups-filters_*.ipk
          openwrt/bin/packages/mips_24kc/base/avahi-*.ipk
